---
# This roles file includes all roles needed for installing 
# complete onecloud stack it also acts as a
roles:
  - src: https://github.com/jimboolio/myorg.ansible_a.git
    scm: git
    version: master
    name: myorg.ansible_a
